import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "ABC webSite",
  description: "Generated by create next app",
  icons:
    "https://www.drupal.org/files/project-images/nextjs-icon-dark-background.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
